stages:
  - qa-python-selenium-test

test_web:
  image: 'rapidfort/python-chromedriver'
  stage: qa-python-selenium-test
  cache:
    key: $CI_COMMIT_REF_NAME
    policy: push
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    paths:
      - test/reports/results.html
      - test/reports/results.json
  script:
    - echo $LOGIN_MYSTORY
    - cd test
    - pip install -r requirements/requirements.txt
    - behave -f html -o=reports/results.html -f json -o=reports/results.json -k
  environment:
    name: $CI_COMMIT_REF_NAME